name: clima
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  weather: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
     - images/


  fonts:
    - family: Spartan MB
      fonts:
             - asset: fonts/SpartanMB-Black.otf
               weight: 900